CREATE TABLE CLIENTES(
    CLIENTE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(40) NOT NULL,
    APELLIDO VARCHAR(40) NOT NULL,
    EMAIL VARCHAR(40) NOT NULL,
    PW VARCHAR(40) NOT NULL
);

CREATE TABLE PRODUCTOS(
    PRODUCTO_ID INT AUTO_INCREMENT PRIMARY KEY,
    SKU VARCHAR(10) NOT NULL,
    CLASS CHAR NOT NULL,
    NOMBRE VARCHAR(40) NOT NULL,
    DESCRIPCION VARCHAR(200) NOT NULL,
    IMAGEN_PATH VARCHAR(50) NOT NULL,
    PRECIO DECIMAL(8,2) NOT NULL,
    EXISTENCIA VARCHAR(40) NOT NULL
);

CREATE TABLE PEDIDOS(
    PEDIDO_ID INT AUTO_INCREMENT PRIMARY KEY,
    FOLIO VARCHAR(10) NOT NULL,
    FECHA DATE NOT NULL,
    COSTO DECIMAL(8,2),
    CLIENTE_ID INT NOT NULL,
    FOREIGN KEY(CLIENTE_ID)
        REFERENCES CLIENTES(CLIENTE_ID)
);

CREATE TABLE PEDIDO_PRODUCTO(
    PEDIDO_PRODUCTO_ID INT AUTO_INCREMENT PRIMARY KEY,
    CANTIDAD INT NOT NULL,
    PEDIDOS_ID INT NOT NULL,
    PRODUCTO_ID INT NOT NULL,
    FOREIGN KEY (PEDIDOS_ID)
        REFERENCES PEDIDOS(PEDIDO_ID),
    FOREIGN KEY (PRODUCTO_ID)
        REFERENCES PRODUCTOS(PRODUCTO_ID)
);

INSERT